#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 DataOnline. DataOnline OpenClaw Auto-Installer.
#
# install-core.sh — Docker, thư mục triển khai, compose, khởi động stack
# Phụ thuộc khi chạy độc lập: utils.sh, checks.sh, ufw.sh
# -----------------------------------------------------------------------------

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=utils.sh
source "${SCRIPT_DIR}/utils.sh"
# shellcheck source=checks.sh
source "${SCRIPT_DIR}/checks.sh"
# shellcheck source=ufw.sh
source "${SCRIPT_DIR}/ufw.sh"

INSTALL_DIR="/opt/dataonline/openclaw"
OPENCLAW_IMAGE="ghcr.io/openclaw/openclaw:latest"
GATEWAY_PORT=18789
BRIDGE_PORT=18790

# -----------------------------------------------------------------------------
# Docker CE + compose plugin (Ubuntu)
# -----------------------------------------------------------------------------
install_docker() {
    if command -v docker &>/dev/null && command -v docker compose &>/dev/null; then
        print_success "Docker đã được cài đặt: $(docker --version)"
        return 0
    fi

    print_info "Đang cài đặt Docker..."
    apt-get update -qq
    apt-get install -y -qq ca-certificates curl gnupg
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
    # shellcheck source=/dev/null
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "${VERSION_CODENAME:-$UBUNTU_CODENAME}") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
    apt-get update -qq
    apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    systemctl enable docker
    systemctl start docker
    print_success "Docker đã được cài đặt thành công."
}

# -----------------------------------------------------------------------------
# /opt/dataonline/openclaw: .env, config/openclaw.json, quyền uid 1000
# -----------------------------------------------------------------------------
setup_install_dir() {
    mkdir -p "${INSTALL_DIR}"/{config,workspace}
    chmod 755 "${INSTALL_DIR}"

    local env_file="${INSTALL_DIR}/.env"
    cat > "${env_file}" << EOF
# DataOnline OpenClaw - Generated by installer
OPENCLAW_IMAGE=${OPENCLAW_IMAGE}
OPENCLAW_CONFIG_DIR=${INSTALL_DIR}/config
OPENCLAW_WORKSPACE_DIR=${INSTALL_DIR}/workspace
OPENCLAW_GATEWAY_PORT=${GATEWAY_PORT}
OPENCLAW_BRIDGE_PORT=${BRIDGE_PORT}
OPENCLAW_GATEWAY_BIND=lan
OPENCLAW_GATEWAY_TOKEN=$(openssl rand -hex 32)
OPENCLAW_TZ=Asia/Ho_Chi_Minh
EOF

    chmod 600 "${env_file}"

    # openclaw.json tối thiểu — tránh lỗi thiếu config khi gateway start
    local config_dir="${INSTALL_DIR}/config"
    local config_file="${config_dir}/openclaw.json"
    if [[ ! -f "${config_file}" ]]; then
        # Không bật dangerouslyAllowHostHeaderOriginFallback — security audit báo DANGEROUS / hạ chống DNS rebinding.
        # Control UI: ưu tiên http://127.0.0.1 hoặc HTTPS + allowedOrigins theo proxy. Chi tiết: docs.openclaw.ai/gateway/security
        cat > "${config_file}" << JSONEOF
{
  "gateway": {
    "mode": "local",
    "controlUi": {
      "allowedOrigins": [
        "http://127.0.0.1:${GATEWAY_PORT}",
        "http://localhost:${GATEWAY_PORT}"
      ]
    }
  },
  "tools": {
    "web": {
      "search": {
        "enabled": false
      }
    }
  }
}
JSONEOF
        chmod 644 "${config_file}"
        print_success "Đã tạo config openclaw.json"
    fi

    # Container chạy user node (1000) — cần ghi config/workspace
    chown -R 1000:1000 "${config_dir}" "${INSTALL_DIR}/workspace"
    print_success "Đã tạo cấu trúc thư mục và file .env"
}

# -----------------------------------------------------------------------------
# Ghi docker-compose.yml (heredoc literal — biến do .env thay thế lúc chạy compose)
# -----------------------------------------------------------------------------
setup_docker_compose() {
    local compose_file="${INSTALL_DIR}/docker-compose.yml"
    cat > "${compose_file}" << 'COMPOSE_EOF'
services:
  openclaw-gateway:
    image: ${OPENCLAW_IMAGE}
    env_file: .env
    environment:
      HOME: /home/node
      TERM: xterm-256color
      OPENCLAW_GATEWAY_TOKEN: ${OPENCLAW_GATEWAY_TOKEN}
      OPENCLAW_ALLOW_INSECURE_PRIVATE_WS: ${OPENCLAW_ALLOW_INSECURE_PRIVATE_WS:-}
      TZ: ${OPENCLAW_TZ:-UTC}
    volumes:
      - ${OPENCLAW_CONFIG_DIR}:/home/node/.openclaw
      - ${OPENCLAW_WORKSPACE_DIR}:/home/node/.openclaw/workspace
    ports:
      - "${OPENCLAW_GATEWAY_PORT:-18789}:18789"
      - "${OPENCLAW_BRIDGE_PORT:-18790}:18790"
    init: true
    restart: unless-stopped
    command:
      - sh
      - -c
      - |
        mkdir -p /home/node/.openclaw/extensions
        ln -sfn /app/extensions/shared /home/node/.openclaw/extensions/shared 2>/dev/null || true
        exec node dist/index.js gateway --bind ${OPENCLAW_GATEWAY_BIND:-lan} --port 18789
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://127.0.0.1:18789/healthz').then((r)=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s

  openclaw-cli:
    image: ${OPENCLAW_IMAGE}
    network_mode: "service:openclaw-gateway"
    cap_drop:
      - NET_RAW
      - NET_ADMIN
    security_opt:
      - no-new-privileges:true
    env_file: .env
    environment:
      HOME: /home/node
      TERM: xterm-256color
      OPENCLAW_GATEWAY_TOKEN: ${OPENCLAW_GATEWAY_TOKEN}
      BROWSER: echo
      TZ: ${OPENCLAW_TZ:-UTC}
    volumes:
      - ${OPENCLAW_CONFIG_DIR}:/home/node/.openclaw
      - ${OPENCLAW_WORKSPACE_DIR}:/home/node/.openclaw/workspace
    stdin_open: true
    tty: true
    init: true
    entrypoint: ["node", "dist/index.js"]
    depends_on:
      - openclaw-gateway
COMPOSE_EOF
    print_success "Đã tạo docker-compose.yml"
}

# -----------------------------------------------------------------------------
# Pull image + docker compose up -d
# -----------------------------------------------------------------------------
start_openclaw() {
    cd "${INSTALL_DIR}"
    print_info "Đang khởi động OpenClaw..."
    docker compose pull -q
    docker compose up -d
    print_success "OpenClaw đã khởi động."
}

# -----------------------------------------------------------------------------
# Luồng cài đặt đầy đủ (gọi từ install.sh menu 1)
# -----------------------------------------------------------------------------
do_install() {
    print_header "DATAONLINE — BẮT ĐẦU CÀI ĐẶT OPENCLAW"
    check_root || exit 1
    check_ubuntu_version || exit 1
    check_ram || exit 1
    check_ports || exit 1
    check_network || { print_error "Không thể kết nối mạng. Kiểm tra kết nối Internet."; exit 1; }
    install_docker
    setup_install_dir
    setup_docker_compose
    start_openclaw
    configure_ufw
    print_success "Cài đặt hoàn tất!"
    echo ""
    print_info "Được phát triển bởi DataOnline — VPS • Hosting • Server tại Việt Nam"
    echo ""
    local ip
    ip=$(hostname -I | awk '{print $1}')
    print_info "Gateway: http://${ip}:${GATEWAY_PORT}"
    print_info "Gateway Token: $(grep OPENCLAW_GATEWAY_TOKEN "${INSTALL_DIR}/.env" | cut -d= -f2)"
    echo ""
    print_warning "Control UI (web): trình duyệt cần ngữ cảnh bảo mật (HTTPS hoặc localhost). Mở http://${ip}:${GATEWAY_PORT} từ máy khác có thể báo lỗi \"device identity\"."
    print_info "  → Cách thường dùng: SSH tunnel — ssh -N -L ${GATEWAY_PORT}:127.0.0.1:${GATEWAY_PORT} user@${ip} — rồi trên máy bạn mở http://127.0.0.1:${GATEWAY_PORT}"
    print_info "  → Hoặc HTTPS (Caddy/nginx/Tailscale Serve). Chi tiết: https://docs.openclaw.ai/gateway/security"
    echo ""
    print_info "Cấu hình qua CLI: chạy script → chọn 3) Cấu hình OpenClaw (CLI)"
    print_info "  onboard | models set <provider>/<model> | pairing list | pairing approve | devices list | devices approve"
    echo ""
    print_warning "Nếu là VPS cloud (AWS, GCP, DigitalOcean...): mở cổng 18789, 18790 trong Security Group/Firewall của nhà cung cấp."
    echo ""
    print_info "Tài liệu OpenClaw: https://docs.openclaw.ai"
    echo ""
    print_info "Tham gia Group Facebook để nhận hỗ trợ: https://www.facebook.com/groups/openclawselfhosted"
}
